# nixpacks.toml

# Phase to install system packages
[phases.setup]
# List packages needed from the Nix package manager
# 'pkgs.ffmpeg-full' usually provides a comprehensive ffmpeg build
nixPkgs = ["pkgs.ffmpeg-full"]

# Phase for installing application dependencies (Python in this case)
[phases.install]
# Nixpacks usually detects requirements.txt automatically, but explicit is fine
cmds = ["pip install --no-cache-dir -r requirements.txt"]

# Phase defining the start command (Nixpacks uses the Procfile by default)
# [start]
# command = "gunicorn app:app --bind 0.0.0.0:$PORT --preload --timeout 180 --workers 3"
# We comment out the start command here because we want Nixpacks to use the Procfile instead.