# nixpacks.toml

# Phase to install system packages AND ensure specific Python version
[phases.setup]
# List packages needed from the Nix package manager
nixPkgs = [
    "pkgs.python310", # Explicitly request Python 3.10 (match your Dockerfile)
    "pkgs.ffmpeg-full" # Keep ffmpeg
]

# REMOVE the [phases.install] section - let Nixpacks handle Python deps automatically
# based on the Python version specified above.
